# Data Input

In [32]:
from pandas import Series,DataFrame
import numpy as np
from google.colab import drive
import pandas as pd
drive.mount('/content/gdrive')  # link google drive

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [33]:
# ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [34]:
headerlist = list(range(1,35))
headerlist.append("label")
df = pd.read_csv("/content/gdrive/My Drive/機器學習概論/hw3/ionosphere.data", names=headerlist, sep= ',')
DataFrame(df)

1  2        3        4        5  ...       31       32       33       34  label
0    1  0  0.99539 -0.05889  0.85243  ...  0.42267 -0.54487  0.18641 -0.45300      g
1    1  0  1.00000 -0.18829  0.93035  ... -0.16626 -0.06288 -0.13738 -0.02447      b
2    1  0  1.00000 -0.03365  1.00000  ...  0.60436 -0.24180  0.56045 -0.38238      g
3    1  0  1.00000 -0.45161  1.00000  ...  0.25682  1.00000 -0.32382  1.00000      b
4    1  0  1.00000 -0.02401  0.94140  ... -0.05707 -0.59573 -0.04608 -0.65697      g
..  .. ..      ...      ...      ...  ...      ...      ...      ...      ...    ...
346  1  0  0.83508  0.08298  0.73739  ...  0.86660 -0.10714  0.90546 -0.04307      g
347  1  0  0.95113  0.00419  0.95183  ...  0.94066 -0.00035  0.91483  0.04712      g
348  1  0  0.94701 -0.00034  0.93207  ...  0.92459  0.00442  0.92697 -0.00577      g
349  1  0  0.90608 -0.01657  0.98122  ...  0.96022 -0.03757  0.87403 -0.16243      g
350  1  0  0.84710  0.13533  0.73638  ...  0.75747 -0.06678  0.85764 -0.06151      g

[351 rows x 35 columns]

# Data Preproocessing

In [35]:
from sklearn.utils import shuffle #shuffle the data
df_shuff = shuffle(df)

# Train-Test-Split(7:3)

In [36]:
from sklearn.model_selection import train_test_split
X = df_shuff.drop(["label"], axis=1)
y = df_shuff["label"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
train = X_train.copy(deep=False)
train["label"] = y_train

# Validation(5-fold)

In [ ]:
def validation(df_origin,k):
  df_tmp = df_origin.copy(deep=False)
  n = int(df_tmp.shape[0]/k)
  # name variable part+i
  for i in range(1,k+1):
    if(i<k):
      globals()['part'+str(i)] = df_tmp.iloc[n*(i-1):n*i]
    else:
      globals()['part'+str(i)] = df_tmp.iloc[n*(i-1):df_tmp.shape[0]]
  
  for i in range(1,k+1):
    globals()['fold'+str(i)] = pd.DataFrame()
    
  for i in range(1,k+1):
    for j in range(1,k+1):
      if(j!=(k+1-i)):
        globals()['fold'+str(i)] = globals()['fold'+str(i)].append(globals()['part'+str(j)])

  for i in range(1,k+1):
    globals()['fold'+str(i)+'_X_train'] = globals()['fold'+str(i)].drop(['label'], axis=1)
    globals()['fold'+str(i)+'_y_train'] = globals()['fold'+str(i)]['label']
    globals()['fold'+str(i)+'_X_test'] = globals()['part'+str(k+1-i)].drop(['label'], axis=1)
    globals()['fold'+str(i)+'_y_test'] = globals()['part'+str(k+1-i)]['label']

In [38]:
from sklearn.metrics import confusion_matrix
import sklearn.metrics
from sklearn.metrics import accuracy_score

def result_func(model, k):
  for i in range(1,k+1):
    model.fit(globals()['fold'+str(i)+'_X_train'], globals()['fold'+str(i)+'_y_train'])
    globals()['fold'+str(i)+'_score'] = model.score(globals()['fold'+str(i)+'_X_test'], globals()['fold'+str(i)+'_y_test'])

  global c_ave, acc_ave, rec_ave, pre_ave, score_ave
  c_ave = 0
  acc_ave = 0
  rec_ave = 0
  pre_ave = 0
  score_ave = 0
  
  for i in range(1,k+1):
    score_ave += globals()['fold'+str(i)+'_score']

  score_ave = round(score_ave / k,4)

# Grid Search(Poly)

In [39]:
from sklearn.svm import SVC
from tabulate import tabulate

# use grid search to find the best hyperparameter pair for poly and rbf
validation(train,5)
print("grid search for SVM_poly")
best_score_poly = 0
step_poly = 0
for degree in [0.1, 1, 10]:
  for gamma in [0.1, 1, 10]:
    for coef in [0.1, 1, 10]:
      step_poly+=1
      svm_poly_tmp = SVC(kernel='poly', degree=degree, gamma=gamma, coef0=coef)
      result_func(svm_poly_tmp,5)
      globals()['parameter'+str(step_poly)] = [degree, gamma, coef, score_ave]
      if score_ave > best_score_poly:
        best_score_poly = score_ave
        best_parameter_poly = [degree, gamma, coef]

print("best score: ", best_score_poly)
print("best parameter: ", best_parameter_poly)


grid search for SVM_poly
best score:  0.8653
best parameter:  [1, 1, 0.1]


# Question(Poly)

In [40]:
scores = []
for i in range(1, step_poly+1):
  tmp1 = globals()['parameter'+str(i)].copy()
  scores.append(tmp1)

scores.sort(key = lambda s: s[3], reverse = True)
table_head = ["degree", "gamma", "coef", "accuracy", "rank"]
table_data = []

for i in range(1, step_poly+1):
  tmp2 = scores[i-1].copy()
  tmp2.append(i)
  table_data.append(tmp2)

print("compare different parameter for SVM_Poly:")
print("\n",tabulate(table_data, headers=table_head, tablefmt="grid"))

compare different parameter for SVM_Poly:

 +----------+---------+--------+------------+--------+
|   degree |   gamma |   coef |   accuracy |   rank |
+==========+=========+========+============+========+
|      1   |     1   |    0.1 |     0.8653 |      1 |
+----------+---------+--------+------------+--------+
|      1   |     1   |    1   |     0.8653 |      2 |
+----------+---------+--------+------------+--------+
|      1   |     1   |   10   |     0.8653 |      3 |
+----------+---------+--------+------------+--------+
|     10   |    10   |    0.1 |     0.8612 |      4 |
+----------+---------+--------+------------+--------+
|      1   |     0.1 |    0.1 |     0.8571 |      5 |
+----------+---------+--------+------------+--------+
|      1   |     0.1 |    1   |     0.8571 |      6 |
+----------+---------+--------+------------+--------+
|      1   |     0.1 |   10   |     0.8571 |      7 |
+----------+---------+--------+------------+--------+
|      1   |    10   |    0.1 |     0.

# Grid Search(RBF)

In [41]:
print("grid search for SVM_rbf")
best_score_rbf = 0
step_rbf = 0
for gamma in [0.1, 1, 10]:
  step_rbf+=1
  svm_rbf_tmp = SVC(kernel='rbf', gamma=gamma)
  result_func(svm_rbf_tmp,5)
  globals()['parameter'+str(step_rbf)] = [gamma, score_ave]
  if score_ave > best_score_rbf:
    best_score_rbf = score_ave
    best_parameter_rbf = [gamma]

print("best score: ", best_score_rbf)
print("best parameter: ", best_parameter_rbf)

grid search for SVM_rbf
best score:  0.9224
best parameter:  [0.1]


# Question(RBF)

In [42]:
scores = []
for i in range(1, step_rbf+1):
  tmp1 = globals()['parameter'+str(i)].copy()
  scores.append(tmp1)
scores.sort(key = lambda s: s[1], reverse = True)
table_head = ["gamma", "accuracy", "rank"]
table_data = []
for i in range(1, step_rbf+1):
  tmp2 = scores[i-1].copy()
  tmp2.append(i)
  table_data.append(tmp2)

print("compare different parameter for SVM_RBF:")
print("\n",tabulate(table_data, headers=table_head, tablefmt="grid"))

compare different parameter for SVM_RBF:

 +---------+------------+--------+
|   gamma |   accuracy |   rank |
+=========+============+========+
|     0.1 |     0.9224 |      1 |
+---------+------------+--------+
|     1   |     0.8939 |      2 |
+---------+------------+--------+
|    10   |     0.6204 |      3 |
+---------+------------+--------+


# SVM Construct

In [ ]:
svm_linear = SVC(kernel='linear')
svm_poly = SVC(kernel='poly', degree=best_parameter_poly[0], gamma=best_parameter_poly[1], coef0=best_parameter_poly[2])
svm_rbf = SVC(kernel='rbf', gamma=best_parameter_rbf[0])

# Result

In [ ]:
# svm_linear result
svm_linear.fit(X_train, y_train)
svm_linear_pred = svm_linear.predict(X_test)
c_linear = confusion_matrix(y_test, svm_linear_pred)
acc_linear = round(accuracy_score(y_test, svm_linear_pred)*100,2)
rec_linear = sklearn.metrics.recall_score(y_test, svm_linear_pred, average=None)
pre_linear = sklearn.metrics.precision_score(y_test, svm_linear_pred, average=None)
print("svm with linear:")
print("\nAccuracy: {}%".format(acc_linear))
print("confusion matrix:\n", c_linear)
table_head = ["class Name", "Sensitivity(Recall)", "Precision"]
table_data = [["b", "{}%".format(round(rec_linear[0]*100,2)), "{}%".format(round(pre_linear[0]*100,2))],
        ["g", "{}%".format(round(rec_linear[1]*100,2)), "{}%".format(round(pre_linear[1]*100,2))]]
print("\n",tabulate(table_data, headers=table_head, tablefmt="grid"))

# svm_poly result
svm_poly.fit(X_train, y_train)
svm_poly_pred = svm_poly.predict(X_test)
c_poly = confusion_matrix(y_test, svm_poly_pred)
acc_poly = round(accuracy_score(y_test, svm_poly_pred)*100,2)
rec_poly = sklearn.metrics.recall_score(y_test, svm_poly_pred, average=None)
pre_poly = sklearn.metrics.precision_score(y_test, svm_poly_pred, average=None)
print("\nsvm with poly:")
print("\nAccuracy: {}%".format(acc_poly))
print("confusion matrix:\n", c_poly)
table_head = ["class Name", "Sensitivity(Recall)", "Precision"]
table_data = [["b", "{}%".format(round(rec_poly[0]*100,2)), "{}%".format(round(pre_poly[0]*100,2))],
        ["g", "{}%".format(round(rec_poly[1]*100,2)), "{}%".format(round(pre_poly[1]*100,2))]]
print("\n",tabulate(table_data, headers=table_head, tablefmt="grid"))

# svm_rbf result
svm_rbf.fit(X_train, y_train)
svm_rbf_pred = svm_rbf.predict(X_test)
c = confusion_matrix(y_test, svm_rbf_pred)
acc = round(accuracy_score(y_test, svm_rbf_pred)*100,2)
rec = sklearn.metrics.recall_score(y_test, svm_rbf_pred, average=None)
pre = sklearn.metrics.precision_score(y_test, svm_rbf_pred, average=None)
print("\nsvm with rbf:")
print("\nAccuracy: {}%".format(acc))
print("confusion matrix:\n", c)
table_head = ["class Name", "Sensitivity(Recall)", "Precision"]
table_data = [["b", "{}%".format(round(rec[0]*100,2)), "{}%".format(round(pre[0]*100,2))],
        ["g", "{}%".format(round(rec[1]*100,2)), "{}%".format(round(pre[1]*100,2))]]
print("\n",tabulate(table_data, headers=table_head, tablefmt="grid"))

svm with linear:

Accuracy: 89.62%
confusion matrix:
 [[32  7]
 [ 4 63]]

 +--------------+-----------------------+-------------+
| class Name   | Sensitivity(Recall)   | Precision   |
+==============+=======================+=============+
| b            | 82.05%                | 88.89%      |
+--------------+-----------------------+-------------+
| g            | 94.03%                | 90.0%       |
+--------------+-----------------------+-------------+

svm with poly:

Accuracy: 86.79%
confusion matrix:
 [[27 12]
 [ 2 65]]

 +--------------+-----------------------+-------------+
| class Name   | Sensitivity(Recall)   | Precision   |
+==============+=======================+=============+
| b            | 69.23%                | 93.1%       |
+--------------+-----------------------+-------------+
| g            | 97.01%                | 84.42%      |
+--------------+-----------------------+-------------+

svm with rbf:

Accuracy: 94.34%
confusion matrix:
 [[34  5]
 [ 1 66]]

 +-------