# Input data

In [1]:
from pandas import Series,DataFrame
import numpy as np
from google.colab import drive
import pandas as pd

# ignore warnings
import warnings
warnings.filterwarnings('ignore')

# link google drive
drive.mount('/content/gdrive')  

Mounted at /content/gdrive


In [2]:
headerlist = list(range(1,35))
headerlist.append("label")
df = pd.read_csv("/content/gdrive/My Drive/機器學習概論/final_project/Food_Log.csv", encoding = 'unicode_escape')
DataFrame(df)

Food Description  ... Water Intake (fl oz)
0     Premier Protein - Chocolate Shake (Low Fat / L...  ...                   17
1                                   Rigatoni - Rigatoni  ...                   17
2                                 Lidia's - Vodka Sauce  ...                   17
3                      Aladdin - Grilled Chicken Breast  ...                   17
4     Honey Stinger - Gluten Free Organic Cinnamon W...  ...                   17
...                                                 ...  ...                  ...
1203                                          Asparagus  ...                   68
1204                             Aladdin - Garlic Bread  ...                   68
1205                    Outtakes - Garden Salad (Large)  ...                   68
1206                     Bakery - Chocolate Chip Cookie  ...                   68
1207  Thomas - English Muffin With Peanut Butter & B...  ...                   68

[1208 rows x 12 columns]

# Data Visualization

In [3]:
df = df.drop(['Food Description'], axis=1)
df = df.drop(['Serving'], axis=1)
df = df.drop(['Date'], axis=1)
DataFrame(df)

type       Meal  ...  Carbohydrates  Water Intake (fl oz)
0            dessert  Breakfast  ...              5                    17
1             grains      Lunch  ...             42                    17
2     fats&seasoning      Lunch  ...              7                    17
3              meats      Lunch  ...              0                    17
4            dessert      Lunch  ...             21                    17
...              ...        ...  ...            ...                   ...
1203      vegetables     Dinner  ...              5                    68
1204          grains     Dinner  ...             53                    68
1205      vegetables     Dinner  ...             12                    68
1206         dessert     Snacks  ...             17                    68
1207         dessert     Snacks  ...            124                    68

[1208 rows x 9 columns]

In [4]:
df_v = df[df['type']=='vegetables']
for i in df_v.index:
  df['type'].iloc[i] = 'fruits&vegetables'

df_f = df[df['type']=='fruits']
for i in df_f.index:
  df['type'].iloc[i] = 'fruits&vegetables'

In [6]:
from tabulate import tabulate
df_tmp = df.drop(['Meal'], axis=1)
type_head = ["dessert","fats&seasoning","fruits&vegetables","grains","juice","meats"]
meal_head = ['Breakfast','Lunch','Dinner','Snacks']

def show_data(food_class):
  print("\n",food_class,":")
  num = []
  for i in meal_head:
    df_meal = df[df['Meal']==i]
    num.append(df_meal[df_meal['type']==food_class].shape[0])

  num.append(df_tmp[df_tmp['type']==food_class].shape[0])
  meal_table_head = ['meal_type','Breakfast','Lunch','Dinner','Snacks','total']
  meal_table_data = [["count", "{}".format(num[0]), "{}".format(num[1]), "{}".format(num[2]), "{}".format(num[3]), "{}".format(num[4])]]
  print("\n",tabulate(meal_table_data, headers=meal_table_head, tablefmt="grid")) 

  data = [["average", "{}".format(df_tmp[df_tmp['type']==food_class].mean()[0]), "{}".format(df_tmp[df_tmp['type']==food_class].mean()[1]),
        "{}".format(df_tmp[df_tmp['type']==food_class].mean()[2]), "{}".format(df_tmp[df_tmp['type']==food_class].mean()[3]),
        "{}".format(df_tmp[df_tmp['type']==food_class].mean()[4]), "{}".format(df_tmp[df_tmp['type']==food_class].mean()[5]),],
      ["standard deviation", "{}".format(df_tmp[df_tmp['type']==food_class].std()[0]), "{}".format(df_tmp[df_tmp['type']==food_class].std()[1]),
        "{}".format(df_tmp[df_tmp['type']==food_class].std()[2]), "{}".format(df_tmp[df_tmp['type']==food_class].std()[3]),
        "{}".format(df_tmp[df_tmp['type']==food_class].std()[4]), "{}".format(df_tmp[df_tmp['type']==food_class].std()[5])]]
  head = ["feature", "Sugar","Sodium","Fat","Protein","Calories","Carbohydrates","Water Intake(fl oz)"]
  print("\n",tabulate(data, headers=head, tablefmt="grid"))

for i in type_head:
  show_data(i)


 dessert :

 +-------------+-------------+---------+----------+----------+---------+
| meal_type   |   Breakfast |   Lunch |   Dinner |   Snacks |   total |
+=============+=============+=========+==========+==========+=========+
| count       |         153 |      64 |       42 |      193 |     452 |
+-------------+-------------+---------+----------+----------+---------+

 +--------------------+---------+----------+---------+-----------+------------+-----------------+
| feature            |   Sugar |   Sodium |     Fat |   Protein |   Calories |   Carbohydrates |
+====================+=========+==========+=========+===========+============+=================+
| average            | 20.2146 |  208.615 | 11.8009 |    8.1969 |    284.456 |         38.5066 |
+--------------------+---------+----------+---------+-----------+------------+-----------------+
| standard deviation | 21.5373 |  205.202 | 12.6544 |   10.6362 |    207.155 |         30.4423 |
+--------------------+---------+----------

# Data preprocessing

In [84]:
from sklearn.preprocessing import LabelEncoder
df_new = df.astype('category')  #transform data to number
labelencoder=LabelEncoder()
for column in df_new.columns:
    df_new[column] = labelencoder.fit_transform(df_new[column])
DataFrame(df_new)

type  Meal  Sugar  ...  Calories  Carbohydrates  Water Intake (fl oz)
0        0     0      1  ...        64              5                     1
1        3     2      1  ...        93             42                     1
2        1     2      5  ...        36              7                     1
3        5     2      0  ...       102              0                     1
4        0     2     10  ...        56             21                     1
...    ...   ...    ...  ...       ...            ...                   ...
1203     2     1      2  ...        12              5                     4
1204     3     1      2  ...       196             53                     4
1205     2     1      4  ...        21             12                     4
1206     0     3      7  ...        50             17                     4
1207     0     3     46  ...       243            110                     4

[1208 rows x 9 columns]

In [85]:
from sklearn.utils import shuffle #shuffle the data
df_shuff = shuffle(df_new)

# Train_Test_Split

In [86]:
from sklearn.model_selection import train_test_split

for i in range(6):
  globals()['df_tmp'+str(i)] = df_shuff[df_shuff['type']==i]
  globals()['X_'+str(i)] = globals()['df_tmp'+str(i)].drop(['type'], axis=1)
  globals()['y_'+str(i)] = globals()['df_tmp'+str(i)]['type']
  globals()['X_train_'+str(i)], globals()['X_test_'+str(i)], globals()['y_train_'+str(i)], globals()['y_test_'+str(i)] = train_test_split(globals()['X_'+str(i)],globals()['y_'+str(i)],test_size=0.1,random_state=0)
  if(i==0):
    X = globals()['X_'+str(i)]
    y = globals()['y_'+str(i)]
    X_train = globals()['X_train_'+str(i)]
    y_train = globals()['y_train_'+str(i)]
    X_test = globals()['X_test_'+str(i)]
    y_test = globals()['y_test_'+str(i)]
  else:
    X = X.append(globals()['X_'+str(i)])
    y = y.append(globals()['y_'+str(i)])
    X_train = X_train.append(globals()['X_train_'+str(i)])
    y_train = y_train.append(globals()['y_train_'+str(i)])
    X_test = X_test.append(globals()['X_test_'+str(i)])
    y_test = y_test.append(globals()['y_test_'+str(i)])

# Model Construction

In [87]:
from sklearn import datasets 
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
model_dt = DecisionTreeClassifier() 
model_KNN_3 = KNeighborsClassifier(n_neighbors=3) 
model_RF_100 = RandomForestClassifier(n_estimators=100) 

# result

In [88]:
from sklearn.metrics import confusion_matrix
import sklearn.metrics
from sklearn.metrics import accuracy_score


def show_result(model_tmp, model_name):
  model_tmp.fit(X_train, y_train)
  y_pred_model = model_tmp.predict(X_test)

  acc = round(accuracy_score(y_test, y_pred_model)*100,2)
  rec = sklearn.metrics.recall_score(y_test,y_pred_model,average=None)
  pre = sklearn.metrics.precision_score(y_test,y_pred_model,average=None)

  print("holdout with", model_name, ":\n")
  print("\nAccuracy: {}%".format(acc))
  print("confusion matrix:")
  print(confusion_matrix(y_test, y_pred_model))

  head = ["Class Name", "Sensitivity(Recall)", "Precision"]
  data = [["dessert", "{}%".format(round(rec[0]*100,2)), "{}%".format(round(pre[0]*100,2))],
      ["fats&seasoning", "{}%".format(round(rec[1]*100,2)), "{}%".format(round(pre[1]*100,2))],
      ["fruits", "{}%".format(round(rec[2]*100,2)), "{}%".format(round(pre[2]*100,2))],
      ["grains", "{}%".format(round(rec[3]*100,2)), "{}%".format(round(pre[3]*100,2))],
      ["juice", "{}%".format(round(rec[4]*100,2)), "{}%".format(round(pre[4]*100,2))],
      ["meats", "{}%".format(round(rec[5]*100,2)), "{}%".format(round(pre[5]*100,2))]]
  print("\n",tabulate(data, headers=head, tablefmt="grid"))

In [91]:
show_result(model_KNN_3, "KNN(3)")
show_result(model_dt, "Decision Tree")
show_result(model_RF_100, "Random Forest(100)")

holdout with KNN(3) :


Accuracy: 66.13%
confusion matrix:
[[37  3  2  3  1  0]
 [ 7  5  1  0  0  0]
 [ 4  0 17  0  0  0]
 [ 4  1  0 13  0  3]
 [ 6  0  0  0  4  1]
 [ 3  1  0  2  0  6]]

 +----------------+-----------------------+-------------+
| Class Name     | Sensitivity(Recall)   | Precision   |
+================+=======================+=============+
| dessert        | 80.43%                | 60.66%      |
+----------------+-----------------------+-------------+
| fats&seasoning | 38.46%                | 50.0%       |
+----------------+-----------------------+-------------+
| fruits         | 80.95%                | 85.0%       |
+----------------+-----------------------+-------------+
| grains         | 61.9%                 | 72.22%      |
+----------------+-----------------------+-------------+
| juice          | 36.36%                | 80.0%       |
+----------------+-----------------------+-------------+
| meats          | 50.0%                 | 60.0%       |
+-------------